### ISSUE TITLE
[Bug] Corese-server: Creation of blank node named graph makes queries with GRAPH impossible

### ISSUE THREAD

**Issue by MaillPierre** [Wimmics/corese#150]
**Issue Description:**

It is possible to create named graphs with a blank node as its name. Doing so makes any future query searching for graphs fail with an IndexOutOfBoundexception

**Bug Details:**
An update query that generates a new graph named after the object of a triple can generate a graph with a blank node as its name. This makes Corese-server fail any following query using the GRAPH keyword.

**Steps to Reproduce:**

1.
```sparql
PREFIX kgi: <http://ns.inria.fr/kg/index#>
INSERT DATA {
  kgi:test a [] 
} 
```
2. 
```sparql
PREFIX kgi: <http://ns.inria.fr/kg/index#>
INSERT {
  GRAPH ?typeGraph {
    ?typeGraph a kgi:Test
  }
} WHERE {
  ?whatever a ?typeGraph
}
```
3. 
```sparql
SELECT * {
  GRAPH ?g {
    ?s ?p ?o
  }
}
```
returns no results and trigger the following error:
```
jakarta.servlet.ServletException: java.lang.ArrayIndexOutOfBoundsException: Index 12 out of bounds for length 5
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1382) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1304) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080) ~[corese-server-4.4.1.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 12 out of bounds for length 5
	at fr.inria.corese.kgram.core.Memory.getNode(Memory.java:1051) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.getGraphNode(Eval.java:1516) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.and(Eval.java:1400) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.eval(Eval.java:1162) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.subEval(Eval.java:512) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.subEval(Eval.java:566) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.EvalGraph.graph(EvalGraph.java:180) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.EvalGraph.graphNodes(EvalGraph.java:116) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.EvalGraph.eval(EvalGraph.java:40) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.eval(Eval.java:1179) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.and(Eval.java:1413) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.eval(Eval.java:1162) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.evalExp(Eval.java:384) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.eval(Eval.java:376) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.query(Eval.java:326) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.queryWE(Eval.java:301) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.eval(Eval.java:276) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.queryBasic(Eval.java:212) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.query(Eval.java:199) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.compiler.eval.QuerySolver.query(QuerySolver.java:335) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.basicQuery(QueryProcess.java:988) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.synQuery(QueryProcess.java:980) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.basicQueryProcess(QueryProcess.java:805) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.basicQuery(QueryProcess.java:760) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.query(QueryProcess.java:546) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.doQuery(QueryProcess.java:542) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.query(QueryProcess.java:508) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.query(QueryProcess.java:512) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.server.webservice.TripleStore.query(TripleStore.java:219) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.server.webservice.SPARQLResult.getResultFormat(SPARQLResult.java:102) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.server.webservice.SPARQLRestAPI.getResultFormat(SPARQLRestAPI.java:331) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.server.webservice.SPARQLRestAPI.getTriplesXMLForPost(SPARQLRestAPI.java:643) ~[corese-server-4.4.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[corese-server-4.4.1.jar:?]
	... 31 more
2023-10-26 18:22:40 WARN  server.HttpChannelState.onError:781 [] - unhandled due to prior sendError
jakarta.servlet.ServletException: java.lang.ArrayIndexOutOfBoundsException: Index 12 out of bounds for length 5
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1382) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1304) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936) ~[corese-server-4.4.1.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080) ~[corese-server-4.4.1.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 12 out of bounds for length 5
	at fr.inria.corese.kgram.core.Memory.getNode(Memory.java:1051) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.getGraphNode(Eval.java:1516) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.and(Eval.java:1400) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.eval(Eval.java:1162) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.subEval(Eval.java:512) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.subEval(Eval.java:566) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.EvalGraph.graph(EvalGraph.java:180) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.EvalGraph.graphNodes(EvalGraph.java:116) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.EvalGraph.eval(EvalGraph.java:40) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.eval(Eval.java:1179) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.and(Eval.java:1413) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.eval(Eval.java:1162) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.evalExp(Eval.java:384) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.eval(Eval.java:376) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.query(Eval.java:326) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.queryWE(Eval.java:301) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.eval(Eval.java:276) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.queryBasic(Eval.java:212) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.kgram.core.Eval.query(Eval.java:199) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.compiler.eval.QuerySolver.query(QuerySolver.java:335) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.basicQuery(QueryProcess.java:988) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.synQuery(QueryProcess.java:980) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.basicQueryProcess(QueryProcess.java:805) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.basicQuery(QueryProcess.java:760) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.query(QueryProcess.java:546) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.doQuery(QueryProcess.java:542) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.query(QueryProcess.java:508) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.core.query.QueryProcess.query(QueryProcess.java:512) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.server.webservice.TripleStore.query(TripleStore.java:219) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.server.webservice.SPARQLResult.getResultFormat(SPARQLResult.java:102) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.server.webservice.SPARQLRestAPI.getResultFormat(SPARQLRestAPI.java:331) ~[corese-server-4.4.1.jar:?]
	at fr.inria.corese.server.webservice.SPARQLRestAPI.getTriplesXMLForPost(SPARQLRestAPI.java:643) ~[corese-server-4.4.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[corese-server-4.4.1.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[corese-server-4.4.1.jar:?]
	... 31 more

```
**Expected Behavior:**

Either 
- query n°2 should return an error, 
- or it should have an implicit guard that does not create blank node-named graphs
- or query n°3 should not trigger an exception

**Note to Developers:**

Not sure what the actual solution should be, to be honest, but it took me a long time to identify the problem.

**Comment by remiceres** [comment]
Hello Pierre,

Thank you for the report. This issue is now fixed thanks to Olivier and will be available in the next release.
