### ISSUE TITLE
Impossible to read a nquad file

### ISSUE THREAD

**Issue by ErwanDemairy** [Wimmics/corese#23]
When trying to open a .nq file (nquad format), the following exception is thrown:
Exception in thread "AWT-EventQueue-0" org.openrdf.rio.UnsupportedRDFormatException: No parser factory available for RDF format N-Quads (mimeTypes=application/n-quads, text/x-nquads, text/nquads; ext=nq)
    at org.openrdf.rio.Rio.createParser(Rio.java:198)
    at fr.inria.edelweiss.kgtool.load.sesame.ParserLoaderSesame.loadWithSesame(ParserLoaderSesame.java:77)
    at fr.inria.edelweiss.kgtool.load.Load.loadWithSesame(Load.java:681)
    at fr.inria.edelweiss.kgtool.load.Load.parse(Load.java:545)
    at fr.inria.edelweiss.kgtool.load.Load.synLoad(Load.java:530)
    at fr.inria.edelweiss.kgtool.load.Load.localLoad(Load.java:473)
    at fr.inria.edelweiss.kgtool.load.Load.parse(Load.java:380)
    at fr.inria.edelweiss.kgtool.load.Load.parse(Load.java:350)
    at fr.inria.acacia.corese.gui.query.GraphEngine.load(GraphEngine.java:120)
    at fr.inria.acacia.corese.gui.core.MainFrame.load(MainFrame.java:1336)
    at fr.inria.acacia.corese.gui.core.MainFrame.load(MainFrame.java:1251)
    at fr.inria.acacia.corese.gui.core.MainFrame.load(MainFrame.java:1222)
    at fr.inria.acacia.corese.gui.core.MainFrame.loadRDF(MainFrame.java:1205)
    at fr.inria.acacia.corese.gui.core.MainFrame.actionPerformed(MainFrame.java:870)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6516)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6281)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:720)
    at java.awt.EventQueue$4.run(EventQueue.java:718)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

I see two ways to solve this issue:
1. indicate to the user that the library sesame-rio-nquads 2.8.0-beta2 should be added to the classpath ;
2. add the sesame-rio-nquads library to kgtool

**Comment by ocorby** [comment]
Bonjour,

On 08/30/2016 05:34 PM, Erwan Demairy wrote:
> 1. indicate to the user that the library sesame-rio-nquads 2.8.0-beta2 
> should be added to the classpath ;
Cette option.
A+
Olivier
