### ISSUE TITLE
java.lang.NoClassDefFoundError JSONLDTripleCallback                                                                 

### ISSUE THREAD

**Issue by phil9987** [Wimmics/corese#64]
It seems that JSONLDTripleCallback has been renamed to JsonLdTripleCallback in 2014:
https://github.com/jsonld-java/jsonld-java/commit/f5b412ba9346d1363f16482e3ebb8d718e36864b

Currently, the following exception is thrown when executing
```
corese.core.load.Load(<graph>)
```

```
SEVERE: com/github/jsonldjava/core/JSONLDTripleCallback
java.lang.NoClassDefFoundError: com/github/jsonldjava/core/JSONLDTripleCallback
[...]
Caused by: java.lang.ClassNotFoundException: com.github.jsonldjava.core.JSONLDTripleCallback
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

**Comment by remiceres** [comment]
Thank you very much for this contribution !
